FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8501 8000
CMD ["sh", "-c", "streamlit run ui/streamlit_chatbot.py --server.port 8501 & uvicorn src.llm_pipeline:app --host 0.0.0.0 --port 8000"]